### ISSUE TITLE
spod 

### ISSUE THREAD

**Issue by markknol** [MatthijsKamstra/haxephp#1]
I have created some SPOD reference that might be useful to add to your book.  It's a nice markdown with tables and stuff.

(It didn't get in into the manual because of some reason, but it seems it was a good idea to keep it I think it would fit in this gitbook)

https://github.com/HaxeFoundation/HaxeManual/blob/std-spod/md/manual/std-spod.md

Then you can drop [the reference](https://matthijskamstra.github.io/haxephp/10sqlite/example.html) to the old haxe site.

@Simn or do we want this in the manual / code cookbook?

**Comment by MatthijsKamstra** [comment]
Hi @markknol 

I agree it would be better to send all references to the **Haxe  Manual&trade;**.
But not all 'old' information from the old website made their way into the new (and therefore making it not 'old' information). 

This information is probably nothing new for you. 
I am glad to see that you are working on it, but I will wait till it's in the **Haxe  Manual&trade;** 
making it official.

I find the documentation confusing enough as is.

But thanks for reading my tutorial/documentation.
My next documentation project will be "Haxe and Java" but that target has close to none documentation anywhere.

I'll leave this issue open till SPOD hits **Haxe  Manual&trade;**

**Comment by markknol** [comment]
Seems like it is/will be part of ufront https://github.com/HaxeFoundation/HaxeManual/pull/126

**Comment by MatthijsKamstra** [comment]
hmmmm if I read correct; it will be a haxelib. 
Chaos till WWX or Haxe 3.3.0
At least it will not disappear... really don't want to learn SQL-speek

**Comment by markknol** [comment]
Spod is now record-macros haxelib https://github.com/HaxeFoundation/record-macros so this can be closed
